apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "mydeployment.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ template "mydeployment.fullname" . }}

spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ template "mydeployment.fullname" . }}
      release: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app: {{ template "mydeployment.fullname" . }}
        release: {{ .Release.Name }}
        network-service-id: {{ .Values.global.nsId }}
        type: ping
      annotations:
        dzsi.com/dzsx-network-function-id: service:DZSXNetworkFunction:kkproj:0a871939-6c45-46ee-ba9c-7428e6b29b42
        dzsi.com/dzsx-network-function-href: https://10.157.103.1:443/tmf-api/mano/serviceInventory/v4/kkproj/service/service:DZSXNetworkFunction:kkproj:0a871939-6c45-46ee-ba9c-7428e6b29b42
        k8s.v1.cni.cncf.io/networks: '[{"name": {{ .Values.macvlanNetName | quote }},
                                        "namespace": {{ .Values.macvlanNetNamespace | quote }}}]'
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: {{ .Values.metrics.annotations.scrape | quote }}
        prometheus.io/path: {{.Values.metrics.annotations.path }}
        prometheus.io/port: {{.Values.metrics.annotations.port | quote}}
        {{- end }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: network-service-id
                operator: In
                values:
                - {{ .Values.global.nsId }}
              - key: type
                operator: In
                values:
                - pong
            topologyKey: kubernetes.io/hostname
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "mydeployment.fullname" . }}
        image: {{ .Values.image.repository -}} : {{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
